# constants.py
DOHDAI_COEFFICIENT       = 0.042
DRYING_FUEL_COEFFICIENT  = 0.025
BISQUE_FUEL_COEFFICIENT  = 0.04
HASSUI_COEFFICIENT       = 0.04
PAINT_COEFFICIENT        = 0.05
FIRING_GAS_CONSTANT      = 370
MOLD_DIVISOR             = 100
HOURLY_WAGE              = 3000
